version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    # depends_on:
    #   - wordpress
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/
      - ./requirements/nginx/certs:/etc/nginx/ssl
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_USERNAME1: ${DB_USERNAME1}
        DB_PASSWORD1: ${DB_PASSWORD1}
    env_file:
      - .env
    restart: always
    container_name: mariadb
    ports:
      - "3307:3306"
    volumes:
      - ./requirements/mariadb/data:/var/lib/mysql
    