version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d/
      - ./requirements/nginx/certs:/etc/nginx/ssl
      - wp:/var/www/html
    networks:
      - inception
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_USERNAME1: ${DB_USERNAME1}
        DB_PASSWORD1: ${DB_PASSWORD1}
    env_file:
      - .env
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USERNAME1: ${DB_USERNAME1}
        DB_PASSWORD1: ${DB_PASSWORD1}
        DB_HOST: mariadb
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    restart: always
    networks:
      - inception

volumes:
  wp:
    driver_opts:
      type: none
      #device: /home/${USER}/data/wordpress
      device: /Users/lbapart/data/wordpress
      o: bind
  db:
    driver_opts:
      type: none
      #device: /home/${USER}/data/mariadb
      device: /Users/lbapart/data/mariadb
      o: bind
networks:
  inception:
    driver: bridge
    