version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    # depends_on:
    #   - wordpress
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/
      - ./requirements/nginx/certs:/etc/nginx/ssl
    